export const BANNER_LOAD_START = 'BANNER_LOAD_START';
export const BANNER_LOAD_SUCCESS = 'BANNER_LOAD_SUCCESS';
export const BANNER_LOAD_FAIL = 'BANNER_LOAD_FAIL';

export const SET_HOMEPAGE = 'SET_HOMEPAGE';
export const SET_OTHERPAGE = 'SET_OTHERPAGE';
